# Docker Compose for BLE-to-TCP Bridge
# Usage:
#   docker compose up                              # Uses default BLE_ADDRESS below
#   BLE_ADDRESS=XX:XX:XX:XX:XX:XX docker compose up # Override with your device

services:
  ble-bridge:
    image: ghcr.io/yeraze/meshtastic-ble-bridge:latest
    container_name: meshmonitor-ble-bridge
    privileged: true  # Required for BLE hardware access
    ports:
      - "4403:4403"  # Expose TCP bridge port
    restart: unless-stopped
    volumes:
      - /var/run/dbus:/var/run/dbus  # Required for D-Bus/Bluetooth access
      - /var/lib/bluetooth:/var/lib/bluetooth:ro  # Pairing information
      - /etc/avahi/services:/etc/avahi/services  # mDNS autodiscovery
    environment:
      # BLE MAC address of your Meshtastic device
      # Find it using: docker compose run --rm ble-bridge --scan
      # To change: Edit the address below or override with BLE_ADDRESS environment variable
      - BLE_ADDRESS=48:CA:43:59:4C:71
    command: --verbose
    healthcheck:
      test: ["CMD", "python3", "-c", "import socket; s = socket.socket(); s.connect(('localhost', 4403)); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
